version: '3' # docker version
services:
  www:
    image: php:apache
    volumes:
      - "./:/var/www/html" # sync project dir with container web dir
    ports:
      - 88:88
      - 443:443 # for future ssl traffic